Repository Mewtwo2387/silverwolf, pull requests merged in 2024-10, with the labels that each got.

#19 Diversity update
  commands/fakequote.js
  commands/say.js
Labels: bug, documentation, duplicate, enhancement, help wanted, good first issue, invalid, question, wontfix, silverwolf is very hot, scara is very hot, kazuha is very hot, kinich is very hot, keqing is very hot, cyno is very hot, ganyu is very hot, dehya is very hot, hutao is very hot, kokomi is very hot, acheron is very hot, seele is very hot, kiana is very hot, mona is very hot, fischl is very hot, yae is very hot, meltryllis is very cool, gambling is very fun

#20 I called pest control
  classes/silverwolf.js
  commands/8ball.js
  commands/8ball2.js
  commands/avartar.js
  commands/execute.js
Labels: bug, documentation, duplicate, enhancement, help wanted, good first issue, invalid, question, wontfix, silverwolf is very hot, scara is very hot, kazuha is very hot, kinich is very hot, keqing is very hot, cyno is very hot, ganyu is very hot, dehya is very hot, hutao is very hot, kokomi is very hot, acheron is very hot, seele is very hot, kiana is very hot, mona is very hot, fischl is very hot, yae is very hot, meltryllis is very cool, gambling is very fun

#21 artifically inflating playtime with ascension
  classes/database.js
  commands/ascend.js
  commands/ascensionupgrade.js
  commands/balance.js
  commands/buy.js
  commands/buyascension.js
  commands/claim.js
  commands/eval.js
  commands/upgrade.js
  utils/ascensionupgrades.js
  utils/upgrades.js
Labels: silverwolf is very hot, scara is very hot, kazuha is very hot, kinich is very hot, keqing is very hot, cyno is very hot, ganyu is very hot, dehya is very hot, hutao is very hot, kokomi is very hot, acheron is very hot, seele is very hot, kiana is very hot, mona is very hot, fischl is very hot, yae is very hot, meltryllis is very cool

#22 Global Error handling
  commands/blame.js
  commands/classes/command.js
Labels: bug, documentation, duplicate, enhancement, help wanted, good first issue, invalid, question, wontfix, silverwolf is very hot, scara is very hot, kazuha is very hot, kinich is very hot, keqing is very hot, cyno is very hot, ganyu is very hot, dehya is very hot, hutao is very hot, kokomi is very hot, acheron is very hot, seele is very hot, kiana is very hot, mona is very hot, fischl is very hot, yae is very hot, meltryllis is very cool, gambling is very fun

#24 We Beta in production 🔥
  classes/database.js
  commands/gacha.js
  commands/grabEmoji.js
  data/characters.json
Labels: bug, documentation, duplicate, enhancement, help wanted, good first issue, invalid, question, wontfix, silverwolf is very hot, scara is very hot, kazuha is very hot, kinich is very hot, keqing is very hot, cyno is very hot, ganyu is very hot, dehya is very hot, hutao is very hot, kokomi is very hot, acheron is very hot, seele is very hot, kiana is very hot, mona is very hot, fischl is very hot, yae is very hot, meltryllis is very cool, gambling is very fun

#25 yolo merge into master
  classes/birthdayScheduler.js
  commands/birthdaySchedulerTest.js
  commands/broadcast.js
Labels: bug, documentation, duplicate, enhancement, help wanted, good first issue, invalid, question, wontfix, silverwolf is very hot, scara is very hot, kazuha is very hot, kinich is very hot, keqing is very hot, cyno is very hot, ganyu is very hot, dehya is very hot, hutao is very hot, kokomi is very hot, acheron is very hot, seele is very hot, kiana is very hot, mona is very hot, fischl is very hot, yae is very hot, meltryllis is very cool, gambling is very fun

#26 I need to shit so i gotta make this quick.
  classes/database.js
  commands/catPic.js
  commands/claim.js
  commands/classes/command.js
  commands/f1Standings.js
  commands/fakequote.js
  commands/gacha.js
  commands/hilichurl.js
  commands/loveCalulator.js
  commands/nothing.js
  commands/nuggieboard.js
  data/hilichurl.json
  data/keywords.json
  package-lock.json
  package.json
Labels: bug, documentation, duplicate, enhancement, help wanted, good first issue, invalid, question, wontfix, silverwolf is very hot, scara is very hot, kazuha is very hot, kinich is very hot, keqing is very hot, cyno is very hot, ganyu is very hot, dehya is very hot, hutao is very hot, kokomi is very hot, acheron is very hot, seele is very hot, kiana is very hot, mona is very hot, fischl is very hot, yae is very hot, meltryllis is very cool, gambling is very fun

#27 added a guide for the smooth brains
  commands/guide.js
Labels: bug, documentation, duplicate, enhancement, help wanted, good first issue, invalid, question, wontfix, silverwolf is very hot, scara is very hot, kazuha is very hot, kinich is very hot, keqing is very hot, cyno is very hot, dehya is very hot, hutao is very hot, kokomi is very hot, acheron is very hot, seele is very hot, kiana is very hot, mona is very hot, fischl is very hot, yae is very hot, meltryllis is very cool, gambling is very fun

#29 Marrying da homies
  classes/database.js
  commands/CatFact.js
  commands/broadcast.js
  commands/cat.js
  commands/catPic.js
  commands/eat.js
  commands/eatMultiple.js
  commands/f1Standings.js
  commands/marriageDivorce.js
  commands/marriagePropose.js
  commands/marriageStatus.js
  commands/russianRoulette.js
  commands/say.js
Labels: bug, documentation, duplicate, enhancement, help wanted, good first issue, invalid, question, wontfix, silverwolf is very hot, scara is very hot, kazuha is very hot, kinich is very hot, cyno is very hot, ganyu is very hot, dehya is very hot, hutao is very hot, kokomi is very hot, acheron is very hot, kiana is very hot, mona is very hot, fischl is very hot, yae is very hot, meltryllis is very cool, gambling is very fun

#32 Competitive Gambling just dropped!!! 🔥 (and profiles)
  .gitignore
  classes/database.js
  classes/silverwolf.js
  commands/blackjack.js
  commands/gamblerboard.js
  commands/profile.js
  commands/roulette.js
  commands/slots.js
Labels: silverwolf is very hot, gambling is very fun

#33 I took a nice shit recently
  commands/arlecchino.js
  commands/blackjack.js
  commands/claim.js
  commands/fakequote.js
  commands/genshinProfile.js
  commands/marriageDivorce.js
  commands/profile.js
  commands/roulette.js
  commands/slots.js
  data/arlecchino.json
  data/genshinNamecards.json
  data/genshinPfps.json
  utils/divorceSettlement.js
  utils/marriageBenefits.js
Labels: bug, documentation, duplicate, enhancement, help wanted, good first issue, invalid, question, wontfix, silverwolf is very hot, scara is very hot, kazuha is very hot, kinich is very hot, keqing is very hot, cyno is very hot, ganyu is very hot, dehya is very hot, hutao is very hot, kokomi is very hot, acheron is very hot, seele is very hot, kiana is very hot, mona is very hot, fischl is very hot, yae is very hot, meltryllis is very cool, gambling is very fun, Finch says Aventurine is very hot

#34 Unemergency fix profile (i knew the bug a few days ago)
  commands/profile.js
Labels: Finch says Aventurine is very hot

#36 Hsr and game Uid Profiles
  .gitignore
  .json
  classes/database.js
  classes/silverwolf.js
  commands/GameUidDelete.js
  commands/arlecchino.js
  commands/dbdump.js
  commands/fakequote.js
  commands/gameUidGet.js
  commands/gameUidSet.js
  commands/hsrProfiles.js
  commands/profile.js
  commands/rnr.js
  commands/upgradedata.js
  data/hsr.json
  data/hsrAvartars.json
  data/hsrCharacters.json
  data/hsrLC.json
Labels: bug, documentation, duplicate, enhancement, help wanted, good first issue, invalid, question, wontfix, silverwolf is very hot, scara is very hot, kazuha is very hot, kinich is very hot, keqing is very hot, cyno is very hot, ganyu is very hot, dehya is very hot, hutao is very hot, kokomi is very hot, acheron is very hot, seele is very hot, kiana is very hot, mona is very hot, fischl is very hot, yae is very hot, meltryllis is very cool, gambling is very fun, Finch says Aventurine is very hot

#38 blacklisting commands
  .json
  classes/database.js
  classes/silverwolf.js
  commands/configBlacklistCommand.js
  commands/configBlacklistCommandsView.js
  commands/fakequote.js
  data/keywords.json
Labels: bug, documentation, duplicate, enhancement, help wanted, good first issue, invalid, question, wontfix, silverwolf is very hot, scara is very hot, kazuha is very hot, kinich is very hot, keqing is very hot, cyno is very hot, ganyu is very hot, dehya is very hot, hutao is very hot, kokomi is very hot, acheron is very hot, seele is very hot, kiana is very hot, mona is very hot, fischl is very hot, yae is very hot, meltryllis is very cool, gambling is very fun, Finch says Aventurine is very hot

#39 The spooky update
  classes/silverwolf.js
  commands/claim.js
Labels: bug, documentation, duplicate, enhancement, help wanted, good first issue, invalid, question, wontfix, silverwolf is very hot, scara is very hot, kazuha is very hot, kinich is very hot, keqing is very hot, cyno is very hot, ganyu is very hot, dehya is very hot, hutao is very hot, acheron is very hot, seele is very hot, kiana is very hot, mona is very hot, fischl is very hot, yae is very hot, meltryllis is very cool, gambling is very fun, Finch says Aventurine is very hot
